/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Maury-PC' at '09/10/17 20:29' with Gradle 2.14.1
 *
 * @author Maury-PC, @date 09/10/17 20:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
